FROM frolvlad/alpine-glibc:alpine-3.4

MAINTAINER "Adam Dodman <adam.dodman@gmx.com>"

ADD start.sh /

#Add deps, download and extract patchelf, download source code, patch it, update library location with patchelf

RUN apk add --no-cache ca-certificates g++ linux-headers lzo make  openssl zlib-dev \
 && wget -qO- https://github.com/strothj/alpine-patchelf/releases/download/0.9/0.9.tar.gz | tar xz \
 && wget -qO- http://code.kryo.se/iodine/iodine-0.7.0.tar.gz | tar xz \
 && cd iodine-0.7.0/src \
 && wget -qO- https://raw.githubusercontent.com/openwrt/packages/master/net/iodine/patches/100-musl-compatibility.patch | patch \
 && cd .. && make && make install \
 && patchelf --set-interpreter /usr/glibc-compat/lib/ld-linux-x86-64.so.2 /usr/local/sbin/iodined \
 && patchelf --set-interpreter /usr/glibc-compat/lib/ld-linux-x86-64.so.2 /usr/local/sbin/iodine \
 && rm -rf /usr/bin/patchelf \
 && cd .. && rm -rf iodine-0.7.0* \
 && apk del --no-cache ca-certificates g++ linux-headers make openssl zlib-dev \
 && chmod +x /start.sh

EXPOSE 53/udp

CMD ["/start.sh"]
